sonar.projectKey=sams-big-fake-company_vf-northface-web
sonar.organization=sams-big-fake-company

sonar.projectName=vf-northface-web
sonar.projectVersion=1.0

sonar.sources=src
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/.next/**,**/public/**,**/*.d.ts
sonar.coverage.exclusions=**/*
